name: Build and deploy Flutter web app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter config --enable-web

      - run: flutter build web --base-href "/SimpleCrochetCounter/"

      - env:
          GITHUB_TOKEN: ${{ secrets.FLUTTER }}
        run: |
          git checkout -b upload
          git add build/web
          git commit -m "Deploy to upload"
          git push --force https://x-access-token:${{ secrets.FLUTTER }}@github.com/goeunleee/SimpleCrochetCounter.git HEAD:upload
