name: Build and deploy flutter web app

on:
  push:
    branches: ["upload"] # 'upload' 브랜치에 push될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # 레포지토리 체크아웃

      - uses: subosito/flutter-action@v2 # Flutter 액션 사용
        with:
          channel: "stable" # 안정된 채널로 설정

      - run: flutter pub get # 종속성 설치
      - run: flutter config --enable-web # 웹 지원 활성화
      - run: flutter build web --base-href "/${{ github.event.repository.name }}/" # build 설정

      - run: git config user.name "github-actions"
      - run: git config user.email "github-actions@github.com"

      - run: git --work-tree build/web add --all # build/web 폴더의 모든 파일을 git에 추가
      - run: git commit -m "Automatic deployment by github-actions"

      # GitHub Pages에 강제 푸시
      - run: git push origin HEAD:upload --force
