name: Build and deploy Flutter web app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get
      - run: flutter pub upgrade web
      - run: flutter config --enable-web
      - run: flutter build web --base-href "/SimpleCrochetCounter/"

      - env:
          GITHUB_TOKEN: ${{ secrets.FLUTTER }}
        run: |
          git config --global user.name "goeun lee"
          git config --global user.email "goeun3501@gmail.com"
          git checkout -b deploy
          rm -rf ./*  # 기존 파일들 삭제
          cp -r build/web/* .  # build/web 안의 모든 파일을 복사
          git add .
          git commit -m "Deploy web build"
          git push --force https://x-access-token:${{ secrets.FLUTTER }}@github.com/goeunleee/SimpleCrochetCounter.git HEAD:deploy
